# Starts with a Linux image that has the Go compiler pre-installed
FROM golang:1.26.5

WORKDIR /app

# Install minimal tools so your Go 'LookPath' checks actually find them
RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc

# COPY requirements.txt .
# RUN pip3 install --no-cache-dir -r requirements.txt --break-system-packages

# Just copy your module configurations to keep things happy
COPY . .